/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as recieveSol from "./Recieve.sol";
export type { recieveSol };
export type { CrossChainNameServiceLookup } from "./CrossChainNameServiceLookup";
export type { CrossChainNameServiceReceiver } from "./CrossChainNameServiceReceiver";
export type { CrossChainNameServiceRegister } from "./CrossChainNameServiceRegister";
export type { ICrossChainNameServiceLookup } from "./ICrossChainNameServiceLookup";
export type { Lookup } from "./Lookup";
export type { Register } from "./Register";
