/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface RegisterInterface extends utils.Interface {
  functions: {
    "enableChain(uint64,address,uint256)": FunctionFragment;
    "i_lookup()": FunctionFragment;
    "i_router()": FunctionFragment;
    "register(string,address)": FunctionFragment;
    "s_chains(uint256)": FunctionFragment;
    "withdraw(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "enableChain"
      | "i_lookup"
      | "i_router"
      | "register"
      | "s_chains"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "enableChain",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "i_lookup", values?: undefined): string;
  encodeFunctionData(functionFragment: "i_router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "s_chains",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "enableChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_lookup", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "i_router", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "s_chains", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "Log(string)": EventFragment;
    "LogBytes(bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Log"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogBytes"): EventFragment;
}

export interface LogEventObject {
  message: string;
}
export type LogEvent = TypedEvent<[string], LogEventObject>;

export type LogEventFilter = TypedEventFilter<LogEvent>;

export interface LogBytesEventObject {
  data: string;
}
export type LogBytesEvent = TypedEvent<[string], LogBytesEventObject>;

export type LogBytesEventFilter = TypedEventFilter<LogBytesEvent>;

export interface Register extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RegisterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    enableChain(
      chainSelector: PromiseOrValue<BigNumberish>,
      ccnsReceiverAddress: PromiseOrValue<string>,
      gasLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    i_lookup(overrides?: CallOverrides): Promise<[string]>;

    i_router(overrides?: CallOverrides): Promise<[string]>;

    register(
      _name: PromiseOrValue<string>,
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    s_chains(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber] & {
        chainSelector: BigNumber;
        ccnsReceiverAddress: string;
        gasLimit: BigNumber;
      }
    >;

    withdraw(
      beneficiary: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  enableChain(
    chainSelector: PromiseOrValue<BigNumberish>,
    ccnsReceiverAddress: PromiseOrValue<string>,
    gasLimit: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  i_lookup(overrides?: CallOverrides): Promise<string>;

  i_router(overrides?: CallOverrides): Promise<string>;

  register(
    _name: PromiseOrValue<string>,
    _address: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  s_chains(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber] & {
      chainSelector: BigNumber;
      ccnsReceiverAddress: string;
      gasLimit: BigNumber;
    }
  >;

  withdraw(
    beneficiary: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    enableChain(
      chainSelector: PromiseOrValue<BigNumberish>,
      ccnsReceiverAddress: PromiseOrValue<string>,
      gasLimit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    i_lookup(overrides?: CallOverrides): Promise<string>;

    i_router(overrides?: CallOverrides): Promise<string>;

    register(
      _name: PromiseOrValue<string>,
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    s_chains(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber] & {
        chainSelector: BigNumber;
        ccnsReceiverAddress: string;
        gasLimit: BigNumber;
      }
    >;

    withdraw(
      beneficiary: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Log(string)"(message?: null): LogEventFilter;
    Log(message?: null): LogEventFilter;

    "LogBytes(bytes)"(data?: null): LogBytesEventFilter;
    LogBytes(data?: null): LogBytesEventFilter;
  };

  estimateGas: {
    enableChain(
      chainSelector: PromiseOrValue<BigNumberish>,
      ccnsReceiverAddress: PromiseOrValue<string>,
      gasLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    i_lookup(overrides?: CallOverrides): Promise<BigNumber>;

    i_router(overrides?: CallOverrides): Promise<BigNumber>;

    register(
      _name: PromiseOrValue<string>,
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    s_chains(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      beneficiary: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    enableChain(
      chainSelector: PromiseOrValue<BigNumberish>,
      ccnsReceiverAddress: PromiseOrValue<string>,
      gasLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    i_lookup(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    i_router(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    register(
      _name: PromiseOrValue<string>,
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    s_chains(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      beneficiary: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
