/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CrossChainNameServiceLookup } from "./CrossChainNameServiceLookup";
export type { CrossChainNameServiceReceiver } from "./CrossChainNameServiceReceiver";
export type { CrossChainNameServiceRegister } from "./CrossChainNameServiceRegister";
export type { ICrossChainNameServiceLookup } from "./ICrossChainNameServiceLookup";
export type { WhitelistHook } from "./WhitelistHook";
export type { WhitelistMananger } from "./WhitelistMananger";